const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    VIEW_MENU: 'VIEW_MENU',
    HIDE_MENU: 'HIDE_MENU',
    GET_PROJECTS: 'GET_PROJECTS',
    SAVE_PROJECTS: 'SAVE_PROJECTS',
    RESET_PROJECTS: 'RESET_PROJECTS',
}

export default ACTIONS