const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    VIEW_MENU: 'VIEW_MENU',
    HIDE_MENU: 'HIDE_MENU',
    GET_PROJECTS: 'GET_PROJECTS',
    SAVE_PROJECTS: 'SAVE_PROJECTS',
    RESET_PROJECTS: 'RESET_PROJECTS',
    GET_WORKBOOKS: 'GET_WORKBOOKS',
    SAVE_WORKBOOKS: 'SAVE_WORKBOOKS',
    RESET_WORKBOOKS: 'RESET_WORKBOOKS',
    GET_QUERIES: 'GET_QUERIES',
    SAVE_QUERIES: 'SAVE_QUERIES',
    RESET_QUERIES: 'RESET_QUERIES',
}

export default ACTIONS
