const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_USER: 'GET_USER',
    GET_ALL_USERS: 'GET_ALL_USERS',
    GET_ALL_STUDENTS: 'GET_ALL_STUDENTS',
    GET_ALL_PROJECTS: 'GET_ALL_PROJECTS',
    GET_ALL_DELIVERIES : 'GET_ALL_DELIVERIES',
    GET_DELIVERIES_BY_STUDENT : 'GET_DELIVERIES_BY_STUDENT',
    GET_ANNUNCIES : 'GET_ANNUNCIES',

}

export default ACTIONS